### PR TITLE
Pythonic Alternative to Construct-based Code

### LINKED ISSUE #44: Rewrite layouts in more Pythonic way
This is the layouts file: https://github.com/SuperteamDAO/solathon/blob/master/solathon/core/layouts.py
It is using the `construct` library the vastly represents low level language data types and strucutres. It would be nice to have Pythonic alternative to this, which is more readable and flexible, resulting in same output.

### PR DESCRIPTION
**Pull request by suhasasumukh**
This PR replaces the original construct-based code with a more readable and flexible Pythonic alternative. 
It uses data classes, the struct module, and custom pack/unpack functions while preserving the original functionality.

This PR fixes #44

### CODE REVIEW

**Comment by GitBolt** [comment]
Did you test it? The code is not sitting there, it is being used in [Instructions](https://github.com/SuperteamDAO/solathon/blob/163e2332c6f4fae39aa751853fa91ca9e039a03a/solathon/core/instructions.py#L9).
Right now the PR does not make the layouts compatible with instructions. Can you do that and ensure its working fine?

**Comment by suhasasumukh** [comment]
> Did you test it? The code is not sitting there, it is being used in [Instructions](https://github.com/SuperteamDAO/solathon/blob/163e2332c6f4fae39aa751853fa91ca9e039a03a/solathon/core/instructions.py#L9). Right now the PR does not make the layouts compatible with instructions. Can you do that and ensure its working fine?

I dont see any conflict from my side & I have made it compatible with instructions

**Comment by GitBolt** [comment]
Instructions file is not updated tho. How have you made it compatible with it without modifying instructions as per changes made? The functions defined in the layouts file aren't being used to decode instructions in the instructions.py file I mentioned above.

**Comment by GitBolt** [comment]
> > Did you test it? The code is not sitting there, it is being used in [Instructions](https://github.com/SuperteamDAO/solathon/blob/163e2332c6f4fae39aa751853fa91ca9e039a03a/solathon/core/instructions.py#L9). Right now the PR does not make the layouts compatible with instructions. Can you do that and ensure its working fine?
> 
> I dont see any conflict from my side & I have made it compatible with instructions

Instructions file is not updated tho. How have you made it compatible with it without modifying instructions as per changes made? The functions defined in the layouts file aren't being used to decode instructions in the instructions.py file I mentioned above.

**Comment by suhasasumukh** [comment]
> > > Did you test it? The code is not sitting there, it is being used in [Instructions](https://github.com/SuperteamDAO/solathon/blob/163e2332c6f4fae39aa751853fa91ca9e039a03a/solathon/core/instructions.py#L9). Right now the PR does not make the layouts compatible with instructions. Can you do that and ensure its working fine?
> > 
> > 
> > I dont see any conflict from my side & I have made it compatible with instructions
> 
> Instructions file is not updated tho. How have you made it compatible with it without modifying instructions as per changes made? The functions defined in the layouts file aren't being used to decode instructions in the instructions.py file I mentioned above.

ADVANCE_NONCE_ACCOUNT has no arguments, you can keep Pass. If it requires handling in the future, you can replace it

**Comment by GitBolt** [comment]
> > > > Did you test it? The code is not sitting there, it is being used in [Instructions](https://github.com/SuperteamDAO/solathon/blob/163e2332c6f4fae39aa751853fa91ca9e039a03a/solathon/core/instructions.py#L9). Right now the PR does not make the layouts compatible with instructions. Can you do that and ensure its working fine?
> > > 
> > > 
> > > I dont see any conflict from my side & I have made it compatible with instructions
> > 
> > 
> > Instructions file is not updated tho. How have you made it compatible with it without modifying instructions as per changes made? The functions defined in the layouts file aren't being used to decode instructions in the instructions.py file I mentioned above.
> 
> ADVANCE_NONCE_ACCOUNT has no arguments, you can keep Pass. If it requires handling in the future, you can replace it

I'm not sure what you mean here. I never mentioned about advance nonce account. I said that the changes that you have made look fine on surface, but they aren't tested. Because the layouts are supposed to be used in the instructions.py file to build instructions for all these specific actions. Making it Pythonic does not mean replacing data structures coming from `struct` lib and replacing them with `class` or `dataclasses`. It must *compile* down to the specific byte code that is accurate representation of the instruction, which `struct` is doing by default. For example this [build method](https://github.com/SuperteamDAO/solathon/blob/master/solathon/core/instructions.py#L84) ultimately compiles down our code into byte code.

I really don't understand what you are doing here. The code won't even work. You are using plenty of things without defining them. Please ensure your code is working properly before proposing changes. Closing this PR for now.

**Pull request closed without merging**
